### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by plonghurst** [dzaman/google-meet-transcripts#1]
I installed the plugin and even rebooted my machine.  When entering a meeting, the plugin doesn't "light up" and and the orange M doesn't appear in the meeting controls (like in the screenshot).

**Comment by dzaman** [comment]
@plonghurst thanks for filing this issue! I think this may be resolved in version 3 of the extension, which will be available in the Chrome store after it is approved. If you have any other issues please let me know.
